version: '3.5'
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - '5672:5672'
      - '1084:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 12345678
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  fakesmtp:
    image: gessnerfl/fake-smtp-server
    container_name: 'fakesmtp'
    ports:
      - '5025:5025'
      - '1083:5080'

  mongodb:
    image: mongo:5.0.14
    restart: always
    container_name: mongodb_notify
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: taskforce-notify
    ports:
      - "27018:27017"
    volumes:
      - ./db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    container_name: mongo-express-notify
    ports:
      - "1085:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@mongodb:27017/

  taskforce.notify:
    image: taskforce.notify
    depends_on:
      - mongodb
      - mongodb-express
      - rabbitmq
      - fakesmtp
    container_name: taskforce.notify.service
    ports:
      - "3336:3333"
    env_file:
      - ../../environments/.notify.docker.env
