# Create User
POST http://localhost:3333/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "testing@email.com",
  "firstname": "Kilo",
  "lastname": "Byte",
  "city": "Solon",
  "password": "123456789",
  "role": "performer",
  "dataBirth": "1986-11-22"
}

###

# Update User
PUT http://localhost:3333/api/auth/b0bb910c-59af-4726-af35-29a163e8f32d HTTP/1.1
Content-Type: application/json

{
  "password": "505050505"
}

###

# Login User
POST http://localhost:3333/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "testing@email.com",
  "password": "123456789"
}

###
