# Create User
POST http://localhost:7777/api/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "ap@testing.com",
  "firstname": "Andrey",
  "lastname": "Bilont",
  "city": "New City",
  "password": "123456789",
  "role": "performer",
  "dataBirth": "1999-11-22"
}

###

# Login User
POST http://localhost:7777/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "testing@email.com",
  "password": "123456789"
}
